# Generated by Django 5.2.6 on 2025-09-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_classroom_school_group_classroom_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('docente', 'Docente'), ('alumno', 'Alumno'), ('familiar', 'Familiar'), ('direccion', 'Dirección')], max_length=20, null=True),
        ),
    ]
