# Generated by Django 5.2.6 on 2025-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_phone_remove_customuser_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('padre', 'Padre'), ('alumno', 'Alumno'), ('profesor', 'Profesor'), ('director', 'Director'), ('admin', 'Administrador')], max_length=20, null=True),
        ),
    ]
