# Generated by Django 5.2.6 on 2025-09-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcomms', '0002_notificationpreference_tutorfamilylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskRetryLog',
        ),
        migrations.RemoveField(
            model_name='tutorfamilylink',
            name='family',
        ),
        migrations.RemoveField(
            model_name='tutorfamilylink',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
        migrations.DeleteModel(
            name='TutorFamilyLink',
        ),
    ]
