# Generated by Django 5.2.6 on 2025-09-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_rename_message_privatemessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
