# Generated by Django 5.2.6 on 2025-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tarea_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['fecha_entrega', 'hora'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
