# Generated by Django 5.2.6 on 2025-09-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='leida',
            field=models.BooleanField(default=False),
        ),
    ]
