# Generated by Django 5.2.6 on 2025-11-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_aviso_destinatarios_alter_aviso_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='notification',
            name='contenido',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='titulo',
            field=models.CharField(default='Notificación', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
