# Generated by Django 5.2.6 on 2025-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_notification_mensaje_notification_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
