# Generated by Django 5.2.6 on 2025-11-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_aviso_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.privatemessage'),
        ),
    ]
