# Generated by Django 5.2.6 on 2025-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_readreceipt'),
        ('core', '0002_classroom_school_group_classroom_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('stage', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='language',
        ),
        migrations.AddField(
            model_name='announcement',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_groups',
            field=models.ManyToManyField(blank=True, to='core.group'),
        ),
    ]
