# Generated by Django 5.2.6 on 2025-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_classgroup_remove_announcement_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content',
            field=models.TextField(default='Sin contenido'),
        ),
    ]
